### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Dorian399** [marv7000/FastValveMaterial#1]
when i run the FastValveMaterial.py it do nothing, when running it from cmd it says "[FVM] Program terminated with exit code 0"

**Comment by 0x14307** [comment]
did you specify arguments

**Comment by Dorian399** [comment]
could you explain it a bit more i never used python

**Comment by marv7000** [comment]
It has nothing to do with python. The repository contains a file named "config.md" which you need to adjust based on your material setup.
Another possibility could be that you didn't install the dependencies (see README).

**Comment by Dorian399** [comment]
I configured it,the dependencies should be installed using "python -m pip install --upgrade Pillow" And 
"python -m pip install --upgrade numpy" ?

**Comment by 0x14307** [comment]
If you have pip installed, just use pip install

**Comment by marv7000** [comment]
Yes, that's how it's supposed to be installed. Would you mind sharing your image file names and config.md file?

**Comment by Dorian399** [comment]
# Input format ("png", "tga")
tga
# Input naming scheme (The endings of the image names in order: color map, ao map, normal map, gloss/rough map, metal map - If one parameter isn't set to a valid value, the corresponding method won't be called)
_col
_o
_n
_g
_cmask
# Input path
images/
# Map used to determine material name
_n
# Output path (Can also be multiple subfolders, e.g. folder1/folder2/output/ - This path will be referenced in the VMT file!)
folder1/
# Gamma adjustment (0-255) - Only change this from 215 if you know what you're doing, other values might break the PBR effect!
215
# Export converted images as tga as well (False/True)
False
# Material setup ("gloss", "rough")
rough
# Print debug messages (False/True)
True

**Comment by 0x14307** [comment]
> when i run the FastValveMaterial.py it do nothing, when running it from cmd it says "[FVM] Program terminated with exit code 0"

Did you even specify arguments?

Also, paste the image here instead of placing it on a third party website.

**Comment by Dorian399** [comment]
![image](https://user-images.githubusercontent.com/92229312/145115611-2f023a63-13be-433e-9fdf-e4d6534d5285.png)

i dont really know what specify arguments mean,I typed "python FastValveMaterial.py" in the cmd

**Comment by marv7000** [comment]
I think I see the issue. You can't have the images in subfolders for the input (Although you *can* put images from different materials in there) In this case, your images aren't in 'images/' like you specified, but in 'images/body'.
Either move the images to 'images/' or change the config to the new path.

**Comment by Dorian399** [comment]
now its show this in the console 
![image](https://user-images.githubusercontent.com/92229312/145116363-c9cefbb2-96d0-4873-8566-72c1b1168a9f.png)
and then close

when running it in cmd it says
[FVM] Loading:
Material:       body
Color:          images//body_col.tga
Occlusion:      images//body_o.tga
Metalness:      images//body_cmask.tga
Normal:         images//body_n.tga
Glossiness:     images//body_g.tga

Traceback (most recent call last):
  File "C:\Users\Lenovo\Downloads\FastValveMaterial_1207\FastValveMaterial.py", line 289, in <module>
    glossImage = convert_roughness_to_gloss(glossImage)
  File "C:\Users\Lenovo\Downloads\FastValveMaterial_1207\FastValveMaterial.py", line 118, in convert_roughness_to_gloss
    return ImageOps.invert(mIm)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageOps.py", line 526, in invert
    return _lut(image, lut)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageOps.py", line 58, in _lut
    raise OSError("not supported for this image mode")
OSError: not supported for this image mode

**Comment by marv7000** [comment]
That's an error on my side, I'll fix it and make a new release.
Thanks for the report.

**Comment by Dorian399** [comment]
ty, should i close the the issue ?

**Comment by marv7000** [comment]
I'll close it when I'm able to confirm that it's working.
I'm assuming this is happening because your image doesn't contain data in all RGBA channels.

**Comment by marv7000** [comment]
Alright, this should be fixed now.
