### ISSUE TITLE
Documentation/Code conflict?

### ISSUE THREAD

**Issue by ARealPear** [marv7000/FastValveMaterial#2]
In config.md the 7th line is described as the roughness/glossiness map and the 8th line is described as the metalness map, which makes sense because the 7th line's default is _r for roughness and the 8th's default is _m for metal. But, when running the script the 7th line is described as the metalness map and the 8th is described as the glossiness map. Which is right?
![image](https://user-images.githubusercontent.com/69981765/162090493-2e37e07b-8a48-4423-8720-69bf8fd07cdb.png)
![image](https://user-images.githubusercontent.com/69981765/162090552-83305515-6588-4d67-ba69-7aaff93d4470.png)

**Comment by marv7000** [comment]
That must have slipped in on accident, the config.md is the correct one. I'll fix the issue, but in the meantime you can simply swap the 3 and 4 in lines 306 and 308 in FastValveMaterial.py

**Comment by marv7000** [comment]
Alright, I pushed a fix for it. Let me know if that fixed it.

**Comment by ARealPear** [comment]
works, thanks!
